// vue-ticket-app/src/components/TicketForm.vue
<template>
  <form class="ticket-form" @submit.prevent="handleSubmit">
    <section class="form-grid">
      <section>
        <label>Title</label>
        <input
          v-model="title"
          placeholder="Short descriptive title"
          aria-label="ticket title"
        />
        <p v-if="errors.title" class="error">{{ errors.title }}</p>
      </section>

      <section>
        <label>Status</label>
        <select v-model="status" aria-label="ticket status">
          <option v-for="stat in STATUS_OPTIONS" :key="stat" :value="stat">
            {{ stat.replace('_', ' ') }}
          </option>
        </select>
        <p v-if="errors.status" class="error">{{ errors.status }}</p>
      </section>

      <section>
        <label>Description (optional)</label>
        <textarea
          v-model="description"
          placeholder="More details (optional)"
          aria-label="ticket description"
        ></textarea>
        <p v-if="errors.description" class="error">{{ errors.description }}</p>
      </section>

      <section class="buttons">
        <button type="submit" class="save">Save</button>
        <button
          v-if="onCancel"
          type="button"
          class="cancel"
          @click="onCancel"
        >
          Cancel
        </button>
      </section>
    </section>

    <button
      type="button"
      class="back-btn"
      :disabled="loading"
      @click="handleBackToDashboard"
    >
      <template v-if="loading">
        <svg
          class="spinner"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
        >
          <circle
            class="opacity-25"
            cx="12"
            cy="12"
            r="10"
            stroke="currentColor"
            stroke-width="4"
          ></circle>
          <path
            class="opacity-75"
            fill="currentColor"
            d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"
          ></path>
        </svg>
        <span>Returning...</span>
      </template>
      <template v-else>← Back to Dashboard</template>
    </button>
  </form>
</template>

<script setup>
import { ref, watch} from "vue";
import { useRouter } from "vue-router";
import { STATUS_OPTIONS, validateTicketPayload } from "../utils/validators";
import toast from "vue3-toastify";
import "vue3-toastify/dist/index.css";

const props = defineProps({
  initial: { type: Object, default: () => ({}) },
  onSubmit: { type: Function, required: true },
  onCancel: { type: Function },
});

const title = ref(props.initial.title ?? "");
const status = ref(props.initial.status ?? "open");
const description = ref(props.initial.desc ?? "");
const priority = ref(props.initial.priority ?? "normal");
const errors = ref({});
const loading = ref(false);
const router = useRouter();

function runValidate() {
  const errs = validateTicketPayload({
    title: title.value,
    status: status.value,
    description: description.value,
  });
  errors.value = errs;
  return errs;
}

watch([title, status, description], runValidate);

function handleSubmit() {
  const errs = runValidate();
  if (Object.keys(errs).length) return;

  props.onSubmit({
    title: title.value.trim(),
    status: status.value,
    description: description.value.trim(),
    priority: priority.value,
  });
}

function handleBackToDashboard() {
  loading.value = true;
  toast.success("Returning to Dashboard...");
  setTimeout(() => {
    router.push("/dashboard");
  }, 1000);
}
</script>

<style scoped>
.ticket-form {
  background: white;
  border: 1px solid #d1d5db;
  border-radius: 1rem;
  padding: 1.25rem;
  color: #111827;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.05);
  transition: all 0.3s ease;
}

.ticket-form:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
}

.form-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
}

@media (max-width: 768px) {
  .form-grid {
    grid-template-columns: 1fr;
  }
}

label {
  display: block;
  font-size: 0.875rem;
  font-weight: 500;
  color: #4b5563;
}

input,
select,
textarea {
  margin-top: 0.25rem;
  padding: 0.5rem;
  width: 100%;
  border: 1px solid #9ca3af;
  border-radius: 0.5rem;
  outline: none;
}

input:focus,
select:focus,
textarea:focus {
  border-color: #22c55e;
  box-shadow: 0 0 0 2px rgba(34, 197, 94, 0.2);
}

textarea {
  min-height: 90px;
}

.error {
  color: #f87171;
  font-size: 0.75rem;
  margin-top: 0.25rem;
}

.buttons {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  margin-top: 1rem;
}

button.save {
  background: #06c122;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 0.5rem;
  cursor: pointer;
}

button.cancel {
  background: #c11f06;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 0.5rem;
  cursor: pointer;
}

.back-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  margin-top: 1rem;
  padding: 0.5rem 1rem;
  color: white;
  border: none;
  border-radius: 0.5rem;
  background: #4f46e5;
  cursor: pointer;
  transition: all 0.3s ease;
}

.back-btn:hover {
  background: #4338ca;
}

.back-btn:disabled {
  background: #a5b4fc;
  cursor: not-allowed;
}

.spinner {
  width: 1.25rem;
  height: 1.25rem;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
</style>

// react-ticket-app/src/components/TicketForm.jsx
import { useEffect, useState, useCallback } from "react";
import { STATUS_OPTIONS, validateTicketPayload } from "../utils/validators";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";

function TicketForm({ initial = {}, onSubmit, onCancel }) {
  const [title, setTitle] = useState(initial.title ?? "");
  const [status, setStatus] = useState(initial.status ?? "open");
  const [description, setDescription] = useState(initial.desc ?? "");
  const [priority, setPriority] = useState(initial.priority ?? "normal");
  const [errors, setErrors] = useState({});
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!initial) return;
    setTitle(initial.title ?? "");
    setStatus(initial.status ?? "open");
    setDescription(initial.desc ?? "");
    setPriority(initial.priority ?? "normal");
    setErrors({});
  }, [initial]);

  const runValidate = useCallback(() => {
    const errs = validateTicketPayload({ title, status, description });
    setErrors(errs);
    return errs;
  }, [title, status, description]);

  useEffect(() => {
    runValidate();
  }, [runValidate]);

  const handleSubmit = (e) => {
    e.preventDefault();
    const errs = runValidate();
    if (Object.keys(errs).length) return;
    onSubmit({
      title: title.trim(),
      status,
      description: description.trim(),
      priority,
    });
  };

  function handleBackToDashboard() {
    setLoading(true);
    toast.success("Returning to Dashboard...");
    setTimeout(() => {
      navigate("/dashboard");
    }, 1200); 
  }

  return (
    <form
      onSubmit={handleSubmit}
      className="
    bg-white 
    backdrop-blur-sm 
    border border-gray-400
    rounded-2xl 
    p-5 
    text-black 
    shadow-md 
    hover:shadow-lg 
    transition-all 
    duration-300 
  "
    >
      <section className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <section className="col-span-1">
          <label className="block text-sm font-medium text-gray-600">
            Title
          </label>
          <input
            aria-label="ticket title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="mt-1 p-2 rounded border border-gray-400 focus:ring-2 outline-0 focus:ring-green-400  w-full"
            placeholder="Short descriptive title"
          />
          {errors.title && (
            <p className="text-red-400 text-sm mt-1">{errors.title}</p>
          )}
        </section>
        <section>
          <label className="block text-sm font-medium text-gray-600">
            Status
          </label>
          <select
            aria-label="ticket title"
            value={status}
            onChange={(e) => setStatus(e.target.value)}
            className="mt-1 p-2 rounded border border-gray-400 focus:ring-2 outline-0 focus:ring-green-400 w-full"
          >
            {STATUS_OPTIONS.map((stat) => (
              <option key={stat} value={stat}>
                {stat.replace("_", " ")}
              </option>
            ))}
          </select>
          {errors.status && (
            <p className="text-red-400 text-sm mt-1">{errors.status}</p>
          )}
        </section>
        <section className="mt-4">
          <label className="block text-sm font-medium text-gray-300">
            Description (optional)
          </label>
          <textarea
            aria-label="ticket description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            className="mt-1 p-2 rounded border border-gray-400 focus:ring-2 outline-0 focus:ring-green-400 w-full min-h-[90px]"
            placeholder="More details (optional)"
          />
          {errors.description && (
            <p className="text-red-400 text-sm mt-1">{errors.description}</p>
          )}
        </section>
        <section className="flex items-center mt-4 gap-3">
          <button
            type="submit"
            className="px-4 py-2 bg-[#06c122] text-white rounded"
          >
            Save
          </button>
          {onCancel && (
            <button
              type="button"
              className="px-4 py-2  bg-[#c11f06] text-white rounded"
              onClick={onCancel}
            >
              Cancel
            </button>
          )}
        </section>
      </section>
      <button
        type="button"
        onClick={handleBackToDashboard}
        disabled={loading}
        className={`flex items-center justify-center gap-2 px-4 py-2 rounded-lg text-white transition-all ${
          loading
            ? "bg-indigo-400 cursor-not-allowed"
            : "bg-indigo-600 hover:bg-indigo-700"
        }`}
      >
        {loading ? (
          <>
            <svg
              className="w-5 h-5 animate-spin text-white"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
            >
              <circle
                className="opacity-25"
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="4"
              ></circle>
              <path
                className="opacity-75"
                fill="currentColor"
                d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"
              ></path>
            </svg>
            <span>Returning...</span>
          </>
        ) : (
          "← Back to Dashboard"
        )}
      </button>
    </form>
  );
}
export default TicketForm;
